### PR TITLE
chore: sync changes for Apps management migration to settings

### PR DESCRIPTION
**Pull request by andrey18106**
This PR synchronizes backend logic for ExAppFetcher and required changes for Apps management.

Screen Shot 2024-10-14 at 17 01 48

## TODO

- [ ] Merge with the server PR for settings app changes: https://github.com/nextcloud/server/pull/48665
- [x] Remove old UI parts that are not needed anymore

### CODE REVIEW

**Review by bigcat88 — APPROVED** [review]
Tested, it works

**Review by julien-nc — COMMENTED** [review]
Looks good. I didn't try it with the related server PR.
Do you want to include the changes dropping the UI stuff that is now in server? If so I'll wait for that to make another review.

**Comment by andrey18106** [comment]
> Looks good. I didn't try it with the related server PR. Do you want to include the changes dropping the UI stuff that is now in server? If so I'll wait for that to make another review.

Removed unused UI parts now.

**Review by julien-nc — APPROVED** [review]

**Pull request merged**
